# ~/.config/alacritty/alacritty.toml

[window]
decorations = "None"
opacity = 0.95
dynamic_padding = true
padding = { x = 0, y = 0 }

[font]
size = 10.5
builtin_box_drawing = true
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

[terminal]
shell = { program = "/bin/bash" }

# Zenwritten-aligned terminal theme (matches your Neovim)
[colors.primary]
background = "#191616"
foreground = "#e6e6e6"

[colors.cursor]
text = "#191616"
cursor = "#e6e6e6"

[colors.selection]
background = "#6e7073"
text = "#e6e6e6"

[colors.normal]
black   = "#191616"
red     = "#d54e53"
green   = "#b9ca4a"
yellow  = "#e6c547"
blue    = "#5a747d"
magenta = "#977C71"
cyan    = "#70c0b1"
white   = "#e6e6e6"

[colors.bright]
black   = "#6e7073"
red     = "#ff6666"
green   = "#cde74a"
yellow  = "#f0d35a"
blue    = "#6a8fa3"
magenta = "#b38b7a"
cyan    = "#7ad4c3"
white   = "#ffffff"
