[bar/bottomPanel]
monitor = ${env:MONITOR:}

width = 100%
height = 23
background = #222
bottom = true
font-0 = "JetBrainsMono Nerd Font Mono:size=7.5;1"
override-redirect = false
wm-restack = generic
modules-center = xSpace
modules-right = xWtf xSpace

[module/xSpace]
type = custom/text
content = " "

[module/xWtf]
type = custom/text
content = "----"

# separators 
[module/xSeparator]
type = custom/script
exec = echo " :: "
interval = 9999999  ; effectively never updates
tail = false
